name: owt_fluttify
description: A `Owt` flutter plugin, Powered by `Fluttify` engine.
version: 0.0.1
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  foundation_fluttify: ^0.8.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.fluttify.owt_fluttify
        pluginClass: OwtFluttifyPlugin
      ios:
        pluginClass: OwtFluttifyPlugin