// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:owt_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';



mixin owt_conference_ConferenceClient_ConferenceClientObserver on java_lang_Object {
  

  

  

  

  @mustCallSuper
  Future<void> onStreamAdded(owt_conference_RemoteStream var1) {
    if (var1 is Ref) kNativeObjectPool.add(var1);
  
    if (fluttifyLogEnabled) {
      debugPrint('onStreamAdded::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> onParticipantJoined(owt_conference_Participant var1) {
    if (var1 is Ref) kNativeObjectPool.add(var1);
  
    if (fluttifyLogEnabled) {
      debugPrint('onParticipantJoined::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> onMessageReceived(String var1, String var2, String var3) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onMessageReceived::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> onServerDisconnected() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onServerDisconnected::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
}

