// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:owt_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';

class org_webrtc_RtpTransceiver_RtpTransceiverInit extends java_lang_Object  {
  //region constants
  static const String name__ = 'org.webrtc.RtpTransceiver.RtpTransceiverInit';

  
  //endregion

  //region creators
  static Future<org_webrtc_RtpTransceiver_RtpTransceiverInit> create__() async {
    final int refId = await MethodChannel('com.fluttify/owt_fluttify').invokeMethod('ObjectFactory::createorg_webrtc_RtpTransceiver_RtpTransceiverInit__');
    final object = org_webrtc_RtpTransceiver_RtpTransceiverInit()..refId = refId..tag__ = 'owt_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<org_webrtc_RtpTransceiver_RtpTransceiverInit> create__org_webrtc_RtpTransceiver_RtpTransceiverDirection(org_webrtc_RtpTransceiver_RtpTransceiverDirection direction) async {
    final int refId = await MethodChannel('com.fluttify/owt_fluttify').invokeMethod('ObjectFactory::createorg_webrtc_RtpTransceiver_RtpTransceiverInit__org_webrtc_RtpTransceiver_RtpTransceiverDirection', {"direction": direction.index});
    final object = org_webrtc_RtpTransceiver_RtpTransceiverInit()..refId = refId..tag__ = 'owt_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<org_webrtc_RtpTransceiver_RtpTransceiverInit> create__org_webrtc_RtpTransceiver_RtpTransceiverDirection__List_java_util_List_String__(org_webrtc_RtpTransceiver_RtpTransceiverDirection direction, List<String> streamIds) async {
    final int refId = await MethodChannel('com.fluttify/owt_fluttify').invokeMethod('ObjectFactory::createorg_webrtc_RtpTransceiver_RtpTransceiverInit__org_webrtc_RtpTransceiver_RtpTransceiverDirection__java_util_List_String_', {"direction": direction.index, "streamIds": streamIds});
    final object = org_webrtc_RtpTransceiver_RtpTransceiverInit()..refId = refId..tag__ = 'owt_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<org_webrtc_RtpTransceiver_RtpTransceiverInit>> create_batch__(int length) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('com.fluttify/owt_fluttify').invokeMethod('ObjectFactory::create_batchorg_webrtc_RtpTransceiver_RtpTransceiverInit__', {'length': length});
  
    final List<org_webrtc_RtpTransceiver_RtpTransceiverInit> typedResult = resultBatch.map((result) => org_webrtc_RtpTransceiver_RtpTransceiverInit()..refId = result..tag__ = 'owt_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  static Future<List<org_webrtc_RtpTransceiver_RtpTransceiverInit>> create_batch__org_webrtc_RtpTransceiver_RtpTransceiverDirection(List<org_webrtc_RtpTransceiver_RtpTransceiverDirection> direction) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('com.fluttify/owt_fluttify').invokeMethod('ObjectFactory::create_batchorg_webrtc_RtpTransceiver_RtpTransceiverInit__org_webrtc_RtpTransceiver_RtpTransceiverDirection', [for (int __i__ = 0; __i__ < direction.length; __i__++) {"direction": direction[__i__].index}]);
  
    final List<org_webrtc_RtpTransceiver_RtpTransceiverInit> typedResult = resultBatch.map((result) => org_webrtc_RtpTransceiver_RtpTransceiverInit()..refId = result..tag__ = 'owt_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  static Future<List<org_webrtc_RtpTransceiver_RtpTransceiverInit>> create_batch__org_webrtc_RtpTransceiver_RtpTransceiverDirection__List_java_util_List_String__(List<org_webrtc_RtpTransceiver_RtpTransceiverDirection> direction, List<List<String>> streamIds) async {
    if (direction.length != streamIds.length) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('com.fluttify/owt_fluttify').invokeMethod('ObjectFactory::create_batchorg_webrtc_RtpTransceiver_RtpTransceiverInit__org_webrtc_RtpTransceiver_RtpTransceiverDirection__java_util_List_String_', [for (int __i__ = 0; __i__ < direction.length; __i__++) {"direction": direction[__i__].index, "streamIds": streamIds[__i__]}]);
  
    final List<org_webrtc_RtpTransceiver_RtpTransceiverInit> typedResult = resultBatch.map((result) => org_webrtc_RtpTransceiver_RtpTransceiverInit()..refId = result..tag__ = 'owt_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  //endregion
}

extension org_webrtc_RtpTransceiver_RtpTransceiverInit_Batch on List<org_webrtc_RtpTransceiver_RtpTransceiverInit> {
  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  //endregion
}