// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum org_webrtc_PeerConnection_RtcpMuxPolicy {
  NEGOTIATE /* null */,
  REQUIRE /* null */
}

extension org_webrtc_PeerConnection_RtcpMuxPolicyToX on org_webrtc_PeerConnection_RtcpMuxPolicy {
  int toValue() {
    switch (this) {
      case org_webrtc_PeerConnection_RtcpMuxPolicy.NEGOTIATE: return org_webrtc_PeerConnection_RtcpMuxPolicy.NEGOTIATE.index + 0;
      case org_webrtc_PeerConnection_RtcpMuxPolicy.REQUIRE: return org_webrtc_PeerConnection_RtcpMuxPolicy.REQUIRE.index + 0;
    }
  }
}

extension org_webrtc_PeerConnection_RtcpMuxPolicyFromX on int {
  org_webrtc_PeerConnection_RtcpMuxPolicy toorg_webrtc_PeerConnection_RtcpMuxPolicy() {
    switch (this) {
      
      default: return org_webrtc_PeerConnection_RtcpMuxPolicy.values[this + 0];
    }
  }
}