// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum org_webrtc_PeerConnection_SdpSemantics {
  PLAN_B /* null */,
  UNIFIED_PLAN /* null */
}

extension org_webrtc_PeerConnection_SdpSemanticsToX on org_webrtc_PeerConnection_SdpSemantics {
  int toValue() {
    switch (this) {
      case org_webrtc_PeerConnection_SdpSemantics.PLAN_B: return org_webrtc_PeerConnection_SdpSemantics.PLAN_B.index + 0;
      case org_webrtc_PeerConnection_SdpSemantics.UNIFIED_PLAN: return org_webrtc_PeerConnection_SdpSemantics.UNIFIED_PLAN.index + 0;
    }
  }
}

extension org_webrtc_PeerConnection_SdpSemanticsFromX on int {
  org_webrtc_PeerConnection_SdpSemantics toorg_webrtc_PeerConnection_SdpSemantics() {
    switch (this) {
      
      default: return org_webrtc_PeerConnection_SdpSemantics.values[this + 0];
    }
  }
}