// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum org_webrtc_PeerConnection_TcpCandidatePolicy {
  ENABLED /* null */,
  DISABLED /* null */
}

extension org_webrtc_PeerConnection_TcpCandidatePolicyToX on org_webrtc_PeerConnection_TcpCandidatePolicy {
  int toValue() {
    switch (this) {
      case org_webrtc_PeerConnection_TcpCandidatePolicy.ENABLED: return org_webrtc_PeerConnection_TcpCandidatePolicy.ENABLED.index + 0;
      case org_webrtc_PeerConnection_TcpCandidatePolicy.DISABLED: return org_webrtc_PeerConnection_TcpCandidatePolicy.DISABLED.index + 0;
    }
  }
}

extension org_webrtc_PeerConnection_TcpCandidatePolicyFromX on int {
  org_webrtc_PeerConnection_TcpCandidatePolicy toorg_webrtc_PeerConnection_TcpCandidatePolicy() {
    switch (this) {
      
      default: return org_webrtc_PeerConnection_TcpCandidatePolicy.values[this + 0];
    }
  }
}