// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum org_webrtc_SessionDescription_Type {
  OFFER /* null */,
  PRANSWER /* null */,
  ANSWER /* null */
}

extension org_webrtc_SessionDescription_TypeToX on org_webrtc_SessionDescription_Type {
  int toValue() {
    switch (this) {
      case org_webrtc_SessionDescription_Type.OFFER: return org_webrtc_SessionDescription_Type.OFFER.index + 0;
      case org_webrtc_SessionDescription_Type.PRANSWER: return org_webrtc_SessionDescription_Type.PRANSWER.index + 0;
      case org_webrtc_SessionDescription_Type.ANSWER: return org_webrtc_SessionDescription_Type.ANSWER.index + 0;
    }
  }
}

extension org_webrtc_SessionDescription_TypeFromX on int {
  org_webrtc_SessionDescription_Type toorg_webrtc_SessionDescription_Type() {
    switch (this) {
      
      default: return org_webrtc_SessionDescription_Type.values[this + 0];
    }
  }
}