// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:owt_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';

class org_webrtc_CallSessionFileRotatingLogSink extends java_lang_Object  {
  //region constants
  static const String name__ = 'org.webrtc.CallSessionFileRotatingLogSink';

  
  //endregion

  //region creators
  static Future<org_webrtc_CallSessionFileRotatingLogSink> create__String__int__org_webrtc_Logging_Severity(String dirPath, int maxFileSize, org_webrtc_Logging_Severity severity) async {
    final int refId = await MethodChannel('com.fluttify/owt_fluttify').invokeMethod('ObjectFactory::createorg_webrtc_CallSessionFileRotatingLogSink__String__int__org_webrtc_Logging_Severity', {"dirPath": dirPath, "maxFileSize": maxFileSize, "severity": severity.index});
    final object = org_webrtc_CallSessionFileRotatingLogSink()..refId = refId..tag__ = 'owt_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<org_webrtc_CallSessionFileRotatingLogSink>> create_batch__String__int__org_webrtc_Logging_Severity(List<String> dirPath, List<int> maxFileSize, List<org_webrtc_Logging_Severity> severity) async {
    if (dirPath.length != maxFileSize.length || maxFileSize.length != severity.length) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('com.fluttify/owt_fluttify').invokeMethod('ObjectFactory::create_batchorg_webrtc_CallSessionFileRotatingLogSink__String__int__org_webrtc_Logging_Severity', [for (int __i__ = 0; __i__ < dirPath.length; __i__++) {"dirPath": dirPath[__i__], "maxFileSize": maxFileSize[__i__], "severity": severity[__i__].index}]);
  
    final List<org_webrtc_CallSessionFileRotatingLogSink> typedResult = resultBatch.map((result) => org_webrtc_CallSessionFileRotatingLogSink()..refId = result..tag__ = 'owt_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  static Future<Uint8List> getLogData(String dirPath) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: org.webrtc.CallSessionFileRotatingLogSink::getLogData([\'dirPath\':$dirPath])');
    }
  
    // invoke native method
    final __result__ = await MethodChannel('com.fluttify/owt_fluttify').invokeMethod('org.webrtc.CallSessionFileRotatingLogSink::getLogData', {"dirPath": dirPath});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (__result__ == null) {
      return null;
    } else {
      final __return__ = __result__ as Uint8List;
    
      return __return__;
    }
  }
  
  
  Future<void> dispose() async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: org.webrtc.CallSessionFileRotatingLogSink@$refId::dispose([])');
    }
  
    // invoke native method
    final __result__ = await MethodChannel('com.fluttify/owt_fluttify').invokeMethod('org.webrtc.CallSessionFileRotatingLogSink::dispose', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (__result__ == null) {
      return null;
    } else {
      final __return__ = __result__;
    
      return __return__;
    }
  }
  
  //endregion
}

extension org_webrtc_CallSessionFileRotatingLogSink_Batch on List<org_webrtc_CallSessionFileRotatingLogSink> {
  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  static Future<List<Uint8List>> getLogData_batch(List<String> dirPath) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
  
    // invoke native method
    final resultBatch = await MethodChannel('com.fluttify/owt_fluttify').invokeMethod('org.webrtc.CallSessionFileRotatingLogSink::getLogData_batch', [for (int __i__ = 0; __i__ < dirPath.length; __i__++) {"dirPath": dirPath[__i__]}]);
  
  
    // convert native result to dart side object
    if (resultBatch == null) {
      return null;
    } else {
      final typedResult = (resultBatch as List).cast<Uint8List>().map((__result__) => __result__ as Uint8List).toList();
    
      return typedResult;
    }
  }
  
  
  Future<List<void>> dispose_batch() async {
    if (false) {
      return Future.error('all args must have same length!');
    }
  
    // invoke native method
    final resultBatch = await MethodChannel('com.fluttify/owt_fluttify').invokeMethod('org.webrtc.CallSessionFileRotatingLogSink::dispose_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {"refId": this[__i__].refId}]);
  
  
    // convert native result to dart side object
    if (resultBatch == null) {
      return null;
    } else {
      final typedResult = (resultBatch as List).cast<String>().map((__result__) => __result__).toList();
    
      return typedResult;
    }
  }
  
  //endregion
}