// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:owt_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';

class org_webrtc_Camera2Enumerator extends java_lang_Object with org_webrtc_CameraEnumerator {
  //region constants
  static const String name__ = 'org.webrtc.Camera2Enumerator';

  
  //endregion

  //region creators
  static Future<org_webrtc_Camera2Enumerator> create__android_content_Context(android_content_Context context) async {
    final int refId = await MethodChannel('com.fluttify/owt_fluttify').invokeMethod('ObjectFactory::createorg_webrtc_Camera2Enumerator__android_content_Context', {"context": context.refId});
    final object = org_webrtc_Camera2Enumerator()..refId = refId..tag__ = 'owt_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<org_webrtc_Camera2Enumerator>> create_batch__android_content_Context(List<android_content_Context> context) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('com.fluttify/owt_fluttify').invokeMethod('ObjectFactory::create_batchorg_webrtc_Camera2Enumerator__android_content_Context', [for (int __i__ = 0; __i__ < context.length; __i__++) {"context": context[__i__].refId}]);
  
    final List<org_webrtc_Camera2Enumerator> typedResult = resultBatch.map((result) => org_webrtc_Camera2Enumerator()..refId = result..tag__ = 'owt_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  static Future<bool> isSupported(android_content_Context context) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: org.webrtc.Camera2Enumerator::isSupported([])');
    }
  
    // invoke native method
    final __result__ = await MethodChannel('com.fluttify/owt_fluttify').invokeMethod('org.webrtc.Camera2Enumerator::isSupported', {"context": context is Ref ? (context as Ref)?.refId : context});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (__result__ == null) {
      return null;
    } else {
      final __return__ = __result__;
    
      return __return__;
    }
  }
  
  //endregion
}

extension org_webrtc_Camera2Enumerator_Batch on List<org_webrtc_Camera2Enumerator> {
  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  static Future<List<bool>> isSupported_batch(List<android_content_Context> context) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
  
    // invoke native method
    final resultBatch = await MethodChannel('com.fluttify/owt_fluttify').invokeMethod('org.webrtc.Camera2Enumerator::isSupported_batch', [for (int __i__ = 0; __i__ < context.length; __i__++) {"context": context[__i__].refId}]);
  
  
    // convert native result to dart side object
    if (resultBatch == null) {
      return null;
    } else {
      final typedResult = (resultBatch as List).cast<bool>().map((__result__) => __result__).toList();
    
      return typedResult;
    }
  }
  
  //endregion
}