// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum org_webrtc_DataChannel_State {
  CONNECTING /* null */,
  OPEN /* null */,
  CLOSING /* null */,
  CLOSED /* null */
}

extension org_webrtc_DataChannel_StateToX on org_webrtc_DataChannel_State {
  int toValue() {
    switch (this) {
      case org_webrtc_DataChannel_State.CONNECTING: return org_webrtc_DataChannel_State.CONNECTING.index + 0;
      case org_webrtc_DataChannel_State.OPEN: return org_webrtc_DataChannel_State.OPEN.index + 0;
      case org_webrtc_DataChannel_State.CLOSING: return org_webrtc_DataChannel_State.CLOSING.index + 0;
      case org_webrtc_DataChannel_State.CLOSED: return org_webrtc_DataChannel_State.CLOSED.index + 0;
    }
  }
}

extension org_webrtc_DataChannel_StateFromX on int {
  org_webrtc_DataChannel_State toorg_webrtc_DataChannel_State() {
    switch (this) {
      
      default: return org_webrtc_DataChannel_State.values[this + 0];
    }
  }
}